**Hyperparameter Tuning:**


1.   GridSearchCV
2.   RandomizedSearchCV

In [2]:
# importing the dependencies
import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [3]:
# loading the data from sklearn
breast_cancer_dataset = sklearn.datasets.load_breast_cancer()

In [4]:
# loading the data to a data frame
data_frame = pd.DataFrame(breast_cancer_dataset.data, columns = breast_cancer_dataset.feature_names)

In [5]:
# print the first 5 rows of the dataframe
data_frame.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
# adding the 'target' column to the data frame
data_frame['label'] = breast_cancer_dataset.target

In [7]:
# print the first 5 rows of the dataframe
data_frame.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,label
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [8]:
# number of rows and Columns in this dataset
data_frame.shape

(569, 31)

In [9]:
# checking for missing values
data_frame.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
label                      0
dtype: int64

In [10]:
# checking the distribution of Target Varibale
data_frame['label'].value_counts()

label
1    357
0    212
Name: count, dtype: int64

1 --> Benign

0 --> Malignant

Separating the features and target

In [11]:
X = data_frame.drop(columns='label', axis=1)
Y = data_frame['label']

In [12]:
print(X)

     mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840
1          20.57         17.77          132.90     1326.0          0.08474
2          19.69         21.25          130.00     1203.0          0.10960
3          11.42         20.38           77.58      386.1          0.14250
4          20.29         14.34          135.10     1297.0          0.10030
..           ...           ...             ...        ...              ...
564        21.56         22.39          142.00     1479.0          0.11100
565        20.13         28.25          131.20     1261.0          0.09780
566        16.60         28.08          108.30      858.1          0.08455
567        20.60         29.33          140.10     1265.0          0.11780
568         7.76         24.54           47.92      181.0          0.05263

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419
1             0.07864         0.08690              0.07017         0.1812
2             0.15990         0.19740              0.12790         0.2069
3             0.28390         0.24140              0.10520         0.2597
4             0.13280         0.19800              0.10430         0.1809
..                ...             ...                  ...            ...
564           0.11590         0.24390              0.13890         0.1726
565           0.10340         0.14400              0.09791         0.1752
566           0.10230         0.09251              0.05302         0.1590
567           0.27700         0.35140              0.15200         0.2397
568           0.04362         0.00000              0.00000         0.1587

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33
1                   0.05667  ...        24.990          23.41
2                   0.05999  ...        23.570          25.53
3                   0.09744  ...        14.910          26.50
4                   0.05883  ...        22.540          16.67
..                      ...  ...           ...            ...
564                 0.05623  ...        25.450          26.40
565                 0.05533  ...        23.690          38.25
566                 0.05648  ...        18.980          34.12
567                 0.07016  ...        25.740          39.42
568                 0.05884  ...         9.456          30.37

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560
1             158.80      1956.0           0.12380            0.18660
2             152.50      1709.0           0.14440            0.42450
3              98.87       567.7           0.20980            0.86630
4             152.20      1575.0           0.13740            0.20500
..               ...         ...               ...                ...
564           166.10      2027.0           0.14100            0.21130
565           155.00      1731.0           0.11660            0.19220
566           126.70      1124.0           0.11390            0.30940
567           184.60      1821.0           0.16500            0.86810
568            59.16       268.6           0.08996            0.06444

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601
1             0.2416                0.1860          0.2750
2             0.4504                0.2430          0.3613
3             0.6869                0.2575          0.6638
4             0.4000                0.1625          0.2364
..               ...                   ...             ...
564           0.4107                0.2216          0.2060
565           0.3215                0.1628          0.2572
566           0.3403                0.1418          0.2218
567           0.9387                0.2650          0.4087
568           0.0000                0.0000          0.2871

     worst fractal dimension
0                    0.11890
1                    0.08902
2                    0.08758
3                    0.17300
4                    0.07678
..                       ...
564                  0.07115
565                  0.06637
566                  0.07820
567                  0.12400
568                  0.07039

[569 rows x 30 columns]

In [13]:
print(Y)

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: label, Length: 569, dtype: int64

In [14]:
X = np.asarray(X)
Y = np.asarray(Y)

#**GridSearchCV**

GridSearchCV is used for determining the best parameters for our model

In [15]:
# loading the SVC model
model = SVC()

# hyperparameters

parameters = {
              'kernel':['linear','poly','rbf','sigmoid'],
              'C':[1, 5, 10, 20]
}

In [16]:
# grid search
classifier = GridSearchCV(model, parameters, cv=5)

# fitting the data to our model
classifier.fit(X, Y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 5, 10, 20],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [17]:
classifier.cv_results_

{'mean_fit_time': array([1.75756850e+00, 7.45353699e-03, 8.79545212e-03, 2.54554272e-02,
        3.60304713e+00, 4.50911522e-03, 4.36983109e-03, 1.51514053e-02,
        5.25237708e+00, 4.45880890e-03, 4.27532196e-03, 1.48465633e-02,
        8.42227235e+00, 4.58846092e-03, 4.29110527e-03, 1.48602486e-02]),
 'std_fit_time': array([8.16007318e-01, 2.62272297e-04, 2.82448259e-04, 6.36524427e-04,
        1.08595869e+00, 6.06678768e-04, 1.39444552e-04, 5.73789936e-04,
        1.34008295e+00, 1.27874320e-04, 1.29896954e-04, 7.27429284e-04,
        2.96933641e+00, 1.06963046e-04, 2.25575346e-04, 7.08399056e-04]),
 'mean_score_time': array([0.0015305 , 0.0023684 , 0.00395231, 0.0064733 , 0.00178862,
        0.00154548, 0.00193272, 0.00391946, 0.00123286, 0.00127373,
        0.00181499, 0.00379415, 0.00133181, 0.00124936, 0.00178518,
        0.00383692]),
 'std_score_time': array([2.93177835e-04, 7.07802725e-05, 4.13502626e-04, 3.22814988e-04,
        1.07655407e-03, 1.76189194e-04, 3.34176108e-05, 7.87996452e-05,
        1.89778793e-05, 1.05472672e-05, 6.05860219e-05, 5.06632244e-05,
        2.52343423e-04, 1.42009439e-05, 5.50712031e-05, 5.46542339e-05]),
 'param_C': masked_array(data=[1, 1, 1, 1, 5, 5, 5, 5, 10, 10, 10, 10, 20, 20, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['linear', 'poly', 'rbf', 'sigmoid', 'linear', 'poly',
                    'rbf', 'sigmoid', 'linear', 'poly', 'rbf', 'sigmoid',
                    'linear', 'poly', 'rbf', 'sigmoid'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'poly'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'sigmoid'},
  {'C': 5, 'kernel': 'linear'},
  {'C': 5, 'kernel': 'poly'},
  {'C': 5, 'kernel': 'rbf'},
  {'C': 5, 'kernel': 'sigmoid'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'poly'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'sigmoid'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'poly'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'sigmoid'}],
 'split0_test_score': array([0.94736842, 0.84210526, 0.85087719, 0.54385965, 0.94736842,
        0.88596491, 0.88596491, 0.49122807, 0.93859649, 0.88596491,
        0.87719298, 0.48245614, 0.92982456, 0.87719298, 0.87719298,
        0.47368421]),
 'split1_test_score': array([0.92982456, 0.88596491, 0.89473684, 0.45614035, 0.93859649,
        0.9122807 , 0.92982456, 0.42105263, 0.93859649, 0.92105263,
        0.92105263, 0.40350877, 0.95614035, 0.92105263, 0.92105263,
        0.40350877]),
 'split2_test_score': array([0.97368421, 0.92982456, 0.92982456, 0.46491228, 0.97368421,
        0.92105263, 0.93859649, 0.42105263, 0.97368421, 0.90350877,
        0.9122807 , 0.42105263, 0.95614035, 0.90350877, 0.92105263,
        0.42105263]),
 'split3_test_score': array([0.92105263, 0.94736842, 0.94736842, 0.38596491, 0.92982456,
        0.93859649, 0.94736842, 0.35087719, 0.94736842, 0.93859649,
        0.95614035, 0.34210526, 0.93859649, 0.93859649, 0.94736842,
        0.34210526]),
 'split4_test_score': array([0.95575221, 0.9380531 , 0.9380531 , 0.45132743, 0.96460177,
        0.95575221, 0.95575221, 0.37168142, 0.96460177, 0.95575221,
        0.94690265, 0.36283186, 0.96460177, 0.95575221, 0.9380531 ,
        0.3539823 ]),
 'mean_test_score': array([0.94553641, 0.90866325, 0.91217202, 0.46044093, 0.95081509,
        0.92272939, 0.93150132, 0.41117839, 0.95256948, 0.920975  ,
        0.92271386, 0.40239093, 0.9490607 , 0.91922062, 0.92094395,
        0.39886664]),
 'std_test_score': array([0.01868869, 0.03938232, 0.03544367, 0.05025317, 0.01621632,
        0.02368918, 0.02435811, 0.04857818, 0.01419963, 0.02470123,
        0.02787898, 0.0489065 , 0.01281637, 0.02730027, 0.02410455,
        0.0476401 ]),
 'rank_test_score': array([ 4, 12, 11, 13,  2,  6,  5, 14,  1,  8,  7, 15,  3, 10,  9, 16],
       dtype=int32)}

In [18]:
# best parameters
print(classifier.best_params_)

{'C': 10, 'kernel': 'linear'}

In [19]:
# higest accuracy

highest_accuracy = classifier.best_score_
print(highest_accuracy)

0.9525694767893185

In [20]:
# loading the results to pandas dataframe
result = pd.DataFrame(classifier.cv_results_)
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,1.757569,0.816007,0.001531,0.000293,1,linear,"{'C': 1, 'kernel': 'linear'}",0.947368,0.929825,0.973684,0.921053,0.955752,0.945536,0.018689,4
1,0.007454,0.000262,0.002368,0.000071,1,poly,"{'C': 1, 'kernel': 'poly'}",0.842105,0.885965,0.929825,0.947368,0.938053,0.908663,0.039382,12
2,0.008795,0.000282,0.003952,0.000414,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.850877,0.894737,0.929825,0.947368,0.938053,0.912172,0.035444,11
3,0.025455,0.000637,0.006473,0.000323,1,sigmoid,"{'C': 1, 'kernel': 'sigmoid'}",0.543860,0.456140,0.464912,0.385965,0.451327,0.460441,0.050253,13
4,3.603047,1.085959,0.001789,0.001077,5,linear,"{'C': 5, 'kernel': 'linear'}",0.947368,0.938596,0.973684,0.929825,0.964602,0.950815,0.016216,2
5,0.004509,0.000607,0.001545,0.000176,5,poly,"{'C': 5, 'kernel': 'poly'}",0.885965,0.912281,0.921053,0.938596,0.955752,0.922729,0.023689,6
6,0.004370,0.000139,0.001933,0.000033,5,rbf,"{'C': 5, 'kernel': 'rbf'}",0.885965,0.929825,0.938596,0.947368,0.955752,0.931501,0.024358,5
7,0.015151,0.000574,0.003919,0.000079,5,sigmoid,"{'C': 5, 'kernel': 'sigmoid'}",0.491228,0.421053,0.421053,0.350877,0.371681,0.411178,0.048578,14
8,5.252377,1.340083,0.001233,0.000019,10,linear,"{'C': 10, 'kernel': 'linear'}",0.938596,0.938596,0.973684,0.947368,0.964602,0.952569,0.014200,1
9,0.004459,0.000128,0.001274,0.000011,10,poly,"{'C': 10, 'kernel': 'poly'}",0.885965,0.921053,0.903509,0.938596,0.955752,0.920975,0.024701,8
10,0.004275,0.000130,0.001815,0.000061,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.877193,0.921053,0.912281,0.956140,0.946903,0.922714,0.027879,7
11,0.014847,0.000727,0.003794,0.000051,10,sigmoid,"{'C': 10, 'kernel': 'sigmoid'}",0.482456,0.403509,0.421053,0.342105,0.362832,0.402391,0.048906,15
12,8.422272,2.969336,0.001332,0.000252,20,linear,"{'C': 20, 'kernel': 'linear'}",0.929825,0.956140,0.956140,0.938596,0.964602,0.949061,0.012816,3
13,0.004588,0.000107,0.001249,0.000014,20,poly,"{'C': 20, 'kernel': 'poly'}",0.877193,0.921053,0.903509,0.938596,0.955752,0.919221,0.027300,10
14,0.004291,0.000226,0.001785,0.000055,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.877193,0.921053,0.921053,0.947368,0.938053,0.920944,0.024105,9
15,0.014860,0.000708,0.003837,0.000055,20,sigmoid,"{'C': 20, 'kernel': 'sigmoid'}",0.473684,0.403509,0.421053,0.342105,0.353982,0.398867,0.047640,16

In [21]:
grid_search_result = result[['param_C','param_kernel','mean_test_score']]
grid_search_result

    param_C param_kernel  mean_test_score
0         1       linear         0.945536
1         1         poly         0.908663
2         1          rbf         0.912172
3         1      sigmoid         0.460441
4         5       linear         0.950815
5         5         poly         0.922729
6         5          rbf         0.931501
7         5      sigmoid         0.411178
8        10       linear         0.952569
9        10         poly         0.920975
10       10          rbf         0.922714
11       10      sigmoid         0.402391
12       20       linear         0.949061
13       20         poly         0.919221
14       20          rbf         0.920944
15       20      sigmoid         0.398867

Highest Accuracy = 95.2%

Best Parameters = {'C':10, 'kernel':'linear'}

#**RandomizedSearchCV**

In [22]:
# loading the SVC model
model = SVC()

# hyperparameters

parameters = {
              'kernel':['linear','poly','rbf','sigmoid'],
              'C':[1, 5, 10, 20]
}

In [24]:
# grid search
classifier = RandomizedSearchCV(model, parameters, cv=5)

# fitting the data to our model
classifier.fit(X, Y)

RandomizedSearchCV(cv=5, estimator=SVC(),
                   param_distributions={'C': [1, 5, 10, 20],
                                        'kernel': ['linear', 'poly', 'rbf',
                                                   'sigmoid']})

In [25]:
classifier.cv_results_

{'mean_fit_time': array([1.83620324e+00, 4.51965332e-03, 9.19171433e+00, 7.11292186e+00,
        1.52765274e-02, 3.88174057e-03, 4.33082581e-03, 4.38094139e-03,
        4.66709137e-03, 4.55160141e-03]),
 'std_fit_time': array([1.00700747e+00, 1.27088992e-04, 3.21664436e+00, 3.26782934e+00,
        7.38889690e-04, 1.11630868e-04, 1.72218993e-04, 2.51955764e-04,
        4.49990127e-04, 1.37019670e-04]),
 'mean_score_time': array([0.00148206, 0.00130968, 0.00135264, 0.00140014, 0.00391412,
        0.00133834, 0.00192719, 0.00178437, 0.00206404, 0.00124989]),
 'std_score_time': array([2.38576284e-04, 3.97895966e-05, 2.26698265e-04, 3.01677072e-04,
        8.25998406e-05, 2.72017106e-05, 8.83671246e-05, 8.25037701e-05,
        2.18993579e-04, 8.36111896e-06]),
 'param_kernel': masked_array(data=['linear', 'poly', 'linear', 'linear', 'sigmoid',
                    'poly', 'rbf', 'rbf', 'rbf', 'poly'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[1, 10, 20, 10, 5, 1, 5, 20, 10, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'params': [{'kernel': 'linear', 'C': 1},
  {'kernel': 'poly', 'C': 10},
  {'kernel': 'linear', 'C': 20},
  {'kernel': 'linear', 'C': 10},
  {'kernel': 'sigmoid', 'C': 5},
  {'kernel': 'poly', 'C': 1},
  {'kernel': 'rbf', 'C': 5},
  {'kernel': 'rbf', 'C': 20},
  {'kernel': 'rbf', 'C': 10},
  {'kernel': 'poly', 'C': 20}],
 'split0_test_score': array([0.94736842, 0.88596491, 0.92982456, 0.93859649, 0.49122807,
        0.84210526, 0.88596491, 0.87719298, 0.87719298, 0.87719298]),
 'split1_test_score': array([0.92982456, 0.92105263, 0.95614035, 0.93859649, 0.42105263,
        0.88596491, 0.92982456, 0.92105263, 0.92105263, 0.92105263]),
 'split2_test_score': array([0.97368421, 0.90350877, 0.95614035, 0.97368421, 0.42105263,
        0.92982456, 0.93859649, 0.92105263, 0.9122807 , 0.90350877]),
 'split3_test_score': array([0.92105263, 0.93859649, 0.93859649, 0.94736842, 0.35087719,
        0.94736842, 0.94736842, 0.94736842, 0.95614035, 0.93859649]),
 'split4_test_score': array([0.95575221, 0.95575221, 0.96460177, 0.96460177, 0.37168142,
        0.9380531 , 0.95575221, 0.9380531 , 0.94690265, 0.95575221]),
 'mean_test_score': array([0.94553641, 0.920975  , 0.9490607 , 0.95256948, 0.41117839,
        0.90866325, 0.93150132, 0.92094395, 0.92271386, 0.91922062]),
 'std_test_score': array([0.01868869, 0.02470123, 0.01281637, 0.01419963, 0.04857818,
        0.03938232, 0.02435811, 0.02410455, 0.02787898, 0.02730027]),
 'rank_test_score': array([ 3,  6,  2,  1, 10,  9,  4,  7,  5,  8], dtype=int32)}

In [26]:
# best parameters

best_parameters = classifier.best_params_
print(best_parameters)

{'kernel': 'linear', 'C': 10}

In [27]:
# higest accuracy

highest_accuracy = classifier.best_score_
print(highest_accuracy)

0.9525694767893185

In [30]:
# loading the results to pandas dataframe
result = pd.DataFrame(classifier.cv_results_)
result.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,1.836203,1.007007,0.001482,0.000239,linear,1,"{'kernel': 'linear', 'C': 1}",0.947368,0.929825,0.973684,0.921053,0.955752,0.945536,0.018689,3
1,0.004520,0.000127,0.001310,0.000040,poly,10,"{'kernel': 'poly', 'C': 10}",0.885965,0.921053,0.903509,0.938596,0.955752,0.920975,0.024701,6
2,9.191714,3.216644,0.001353,0.000227,linear,20,"{'kernel': 'linear', 'C': 20}",0.929825,0.956140,0.956140,0.938596,0.964602,0.949061,0.012816,2
3,7.112922,3.267829,0.001400,0.000302,linear,10,"{'kernel': 'linear', 'C': 10}",0.938596,0.938596,0.973684,0.947368,0.964602,0.952569,0.014200,1
4,0.015277,0.000739,0.003914,0.000083,sigmoid,5,"{'kernel': 'sigmoid', 'C': 5}",0.491228,0.421053,0.421053,0.350877,0.371681,0.411178,0.048578,10

In [31]:
randomized_search_result = result[['param_C','param_kernel','mean_test_score']]
randomized_search_result

   param_C param_kernel  mean_test_score
0        1       linear         0.945536
1       10         poly         0.920975
2       20       linear         0.949061
3       10       linear         0.952569
4        5      sigmoid         0.411178
5        1         poly         0.908663
6        5          rbf         0.931501
7       20          rbf         0.920944
8       10          rbf         0.922714
9       20         poly         0.919221

Highest Accuracy = 95.2%

Best Parameters = {'C':10, 'kernel':'linear'}